apiVersion: apps/v1
kind: Deployment
metadata:
  name: veg-app
  namespace: splash-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: veg
  template:
    metadata:
      labels:
        app: veg
    spec:
      containers:
        - name: veg-container
          image: kalyantwt/veg-app:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongodb:27017/vegdb
