apiVersion: apps/v1
kind: Deployment
metadata:
  name: veg-mongodb
  namespace: splash-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veg-mongo
  template:
    metadata:
      labels:
        app: veg-mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
